# deploy-tag: cloud
# deploy-site: eqiad, codfw

groups:
  - name: prometheus
    rules:
    - &job_unavailable
      alert: JobUnavailable
      annotations:
        description: The Prometheus job {{ $labels.job }} running on {{ $externalLabels.prometheus }}@{{ $externalLabels.site }}
          reports {{ $value | humanizePercentage }} of its targets were scrape-able.
          Check if the targets are reachable and exporting metrics.
        summary: Reduced availability for job {{ $labels.job }} in {{ $externalLabels.prometheus }}@{{ $externalLabels.site }}
        dashboard: 'https://grafana.wikimedia.org/d/NEJu05xZz/prometheus-targets'
        runbook: 'https://wikitech.wikimedia.org/wiki/Prometheus#Prometheus_job_unavailable'
      expr: 0.5 >= sum by (job) (up) / count by (job) (up)
      labels:
        severity: critical
        team: wmcs
