rule_files:
  - alertmanager.yaml
evaluation_interval: 1m
tests:
 - interval: 1m
   input_series:
    - series: 'alertmanager_config_last_reload_successful'
      values: '1 1 1 0+0x30'
   external_labels:
     site: eqiad
     prometheus: ops
   alert_rule_test:
    - alertname: AlertManagerInvalidConfig
      eval_time: 30m
      exp_alerts:
       - exp_labels:
           severity: warning
           team: o11y
         exp_annotations:
           summary: AlertManager invalid configuration
           description: AlertManager's configuration is not valid, check the runbook and logs
           dashboard: https://grafana.wikimedia.org/d/eea-9_sik/alertmanager
           runbook: https://wikitech.wikimedia.org/wiki/Alertmanager#Alerts

 - interval: 1m
   input_series:
    - series: 'alertmanager_alerts_received_total'
      values: '1 1 1 0+0x30'
   external_labels:
     site: eqiad
     prometheus: ops
   alert_rule_test:
    - alertname: AlertManagerNoAlerts
      eval_time: 30m
      exp_alerts:
       - exp_labels:
           severity: critical
           team: o11y
         exp_annotations:
           description: AlertManager has not been receiving alerts, check the runbook and logs
           summary: AlertManager is not receiving alerts
           dashboard: https://grafana.wikimedia.org/d/eea-9_sik/alertmanager
           runbook: https://wikitech.wikimedia.org/wiki/Alertmanager#Alerts
       - exp_labels:
           severity: warning
           team: o11y
         exp_annotations:
           description: AlertManager has not been receiving alerts, check the runbook and logs
           summary: AlertManager is not receiving alerts
           dashboard: https://grafana.wikimedia.org/d/eea-9_sik/alertmanager
           runbook: https://wikitech.wikimedia.org/wiki/Alertmanager#Alerts

 - interval: 1m
   input_series:
    - series: 'alertmanager_notifications_failed_total'
      values: '1000+666x20'
   external_labels:
     site: eqiad
     prometheus: ops
   alert_rule_test:
    - alertname: AlertManagerNotificationFail
      eval_time: 10m
      exp_alerts:
       - exp_labels:
           severity: warning
           team: o11y
         exp_annotations:
           description: AlertManager is failing to deliver notifications
           summary: AlertManager is failing to deliver notifications
           dashboard: https://grafana.wikimedia.org/d/eea-9_sik/alertmanager
           runbook: https://wikitech.wikimedia.org/wiki/Alertmanager#Alerts
       - exp_labels:
           severity: critical
           team: o11y
         exp_annotations:
           description: AlertManager is failing to deliver notifications
           summary: AlertManager is failing to deliver notifications
           dashboard: https://grafana.wikimedia.org/d/eea-9_sik/alertmanager
           runbook: https://wikitech.wikimedia.org/wiki/Alertmanager#Alerts

