# deploy-tag: local
# i.e. deploy to all Prometheus instances

groups:
  - name: prometheus
    rules:

    - alert: PrometheusConfigFailure
      annotations:
        description: A failure has been encountered while reloading Prometheus
          configuration. Check logs of instance {{ $externalLabels.prometheus }}
          in {{ $externalLabels.site }}.
        summary: Prometheus/{{ $externalLabels.prometheus }} has failed to reload configuration.
        dashboard: https://grafana.wikimedia.org/d/GWvEXWDZk/prometheus-server?var-datasource={{ $externalLabels.site }}%20prometheus%2F{{ $externalLabels.prometheus }}
        runbook: https://wikitech.wikimedia.org/wiki/Prometheus#Configuration_reload_failure
      expr: prometheus_config_last_reload_successful == 0
      for: 5m
      labels:
        severity: warning
        team: o11y

    - alert: PrometheusRestarted
      annotations:
        description: Prometheus {{ $externalLabels.prometheus }} in {{ $externalLabels.site }}
          has recently restarted. Prometheus restarts can sometimes cause odd
          monitoring artifacts -- missing data, rate computations being lower
          than they should be, etc.
        summary: "Prometheus/{{ $externalLabels.prometheus }} restarted: beware monitoring artifacts."
        dashboard: https://grafana.wikimedia.org/d/GWvEXWDZk/prometheus-server?var-datasource={{ $externalLabels.site }}%20prometheus%2F{{ $externalLabels.prometheus }}
        runbook: https://wikitech.wikimedia.org/wiki/Prometheus#Prometheus_was_restarted
      expr: time() - process_start_time_seconds{job="prometheus"} < 1800
      for: 5m
      labels:
        severity: warning
        team: o11y

    - alert: PrometheusNotConnectedToAM
      annotations:
        description: Prometheus is failing to connect to AlertManager
        summary: Prometheus is failing to connect to AlertManager
        dashboard: https://grafana.wikimedia.org/d/eea-9_sik/alertmanager
        runbook: https://wikitech.wikimedia.org/wiki/Alertmanager#Alerts
      expr: prometheus_notifications_alertmanagers_discovered < 2
      for: 5m
      labels:
        severity: warning
        team: o11y
    - alert: PrometheusNotConnectedToAM
      annotations:
        description: Prometheus is failing to connect to AlertManager
        summary: Prometheus is failing to connect to AlertManager
        dashboard: https://grafana.wikimedia.org/d/eea-9_sik/alertmanager
        runbook: https://wikitech.wikimedia.org/wiki/Alertmanager#Alerts
      expr: prometheus_notifications_alertmanagers_discovered < 1
      for: 5m
      labels:
        severity: critical
        team: o11y

    - alert: PrometheusRuleEvaluationFailures
      expr: increase(prometheus_rule_evaluation_failures_total[3m]) > 0
      for: 0m
      labels:
        severity: critical
        team: o11y
      annotations:
        summary: Prometheus rule evaluation failures (instance {{ $labels.instance }})
        description: "Prometheus encountered {{ $value }} rule evaluation failures, leading to potentially ignored alerts."
        dashboard: https://grafana.wikimedia.org/d/GWvEXWDZk/prometheus-server?var-datasource={{ $externalLabels.site }}%20prometheus%2F{{ $externalLabels.prometheus }}
        runbook: https://wikitech.wikimedia.org/wiki/Prometheus

    - alert: PrometheusTemplateTextExpansionFailures
      expr: increase(prometheus_template_text_expansion_failures_total[3m]) > 0
      for: 0m
      labels:
        severity: critical
        team: o11y
      annotations:
        summary: Prometheus template text expansion failures (instance {{ $labels.instance }})
        description: "Prometheus encountered {{ $value }} template text expansion failures."
        dashboard: https://grafana.wikimedia.org/d/GWvEXWDZk/prometheus-server?var-datasource={{ $externalLabels.site }}%20prometheus%2F{{ $externalLabels.prometheus }}
        runbook: https://wikitech.wikimedia.org/wiki/Prometheus

    - alert: PrometheusRuleEvaluationSlow
      expr: prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds
      for: 5m
      labels:
        severity: warning
        team: o11y
      annotations:
        summary: Prometheus rule evaluation slow (instance {{ $labels.instance }})
        description: "Prometheus rule evaluation took more time than the scheduled interval. It indicates a slower storage backend access or too complex query."
        dashboard: https://grafana.wikimedia.org/d/GWvEXWDZk/prometheus-server?var-datasource={{ $externalLabels.site }}%20prometheus%2F{{ $externalLabels.prometheus }}
        runbook: https://wikitech.wikimedia.org/wiki/Prometheus

    - alert: PrometheusNotificationsBacklog
      expr: min_over_time(prometheus_notifications_queue_length[10m]) > 0
      for: 0m
      labels:
        severity: warning
        team: o11y
      annotations:
        summary: Prometheus notifications backlog (instance {{ $labels.instance }})
        description: "The Prometheus notification queue has not been empty for 10 minutes."
        dashboard: https://grafana.wikimedia.org/d/GWvEXWDZk/prometheus-server?var-datasource={{ $externalLabels.site }}%20prometheus%2F{{ $externalLabels.prometheus }}
        runbook: https://wikitech.wikimedia.org/wiki/Prometheus
